routes/admin.php
<?php
Route::group(['middleware' => ['web','roles']],function(){
    Route::group(['roles'=>['Admin']],function(){
        Route::group([
            'prefix' => 'admin','as' => 'admin.',
        ], function(){
            Route::get('/', 'AdminController@index')->name('admin');
            Route::get('/data_admin','AdminController@data_admin')->name('data_admin');
            Route::get('/json_admin','AdminController@json_admin')->name('json_admin');
            Route::post('/input_admin','AdminController@input_admin')->name('input_admin');
            Route::post('/update_user/{id}','AdminController@update_user')->name('update_user');
            Route::post('/update_foto/{id}','AdminController@update_foto')->name('update_foto');
            Route::get('/update_status/{id}','AdminController@update_status')->name('update_status');
            Route::get('/delete_user/{id}','AdminController@delete_user')->name('delete_user');
        
        });

    });
});
Route::group(['middleware' => ['web','roles']],function(){
    Route::group(['roles'=>['Admin','Guru']],function(){
        Route::group([
            'prefix' => 'admin','as' => 'admin.',
        ], function(){
            Route::post('/update_password/{id}','AdminController@update_password')->name('update_password');
        });

    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/1', function () {
    return view('welcome');
});
Route::get('/link', function () {
    Artisan::call('storage:link');
    }); //untuk membuat storage link
include 'admin.php';
include 'landing.php';
include 'posting.php';

resources/views/admin/data_admin.blade.php
@extends('admin.layout')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Data Admin</h1>
    <p class="mb-4">Berisi tabel yang memuat seluruh data Admin yang bersifat sangat privat dan penting</p>
        <div class="card shadow mb-4">
            <div class="card-body">
                <button type="button" data-toggle="modal" data-target="#exampleModal" class="btn btn-primary">Tambah Admin</button>
            </div>
        </div>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Tabel Data Admin</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table table-bordered" id="admin" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>NO</th>
                <th>FOTO</th>
                <th>NAMA</th>
                <th>EMAIL</th>
                <th>GANTI PASSWORD</th>
                <th>GANTI PROFIL</th>
                <th>STATUS</th>
                <th>PENGATURAN</th>
            </tr>
            </thead>
            
        </table>
        </div>
    </div>
    </div>
</div>
<!-- /.container-fluid -->

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Tambah Admin</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <form class="user" action="{{route('admin.input_admin')}}" method="post">
            @csrf
            <div class="form-group row">
              <div class="col-sm-12 mb-3 mb-sm-0">
                <input type="text" name="nama" class="form-control  " id="exampleFirstName" placeholder="Nama Lengkap">
              </div>
            </div>
            <div class="form-group row">
              <div class="col-sm-12 mb-3 mb-sm-0">
                <input type="text" name="alamat" class="form-control  " id="exampleFirstName" placeholder="Alamat Lengkap">
              </div>
            </div>
            <div class="form-group">
              <input type="email" name="email" class="form-control  " id="exampleInputEmail" placeholder="Email Address">
            </div>
            <div class="form-group">
              <input type="number" name="hp" class="form-control  " placeholder="Nomor Telephone">
            </div>
            <div class="form-group row">
              <div class="col-sm-6 mb-3 mb-sm-0">
                <input type="password" name="password" class="form-control  " id="exampleInputPassword" placeholder="Password">
              </div>
              <div class="col-sm-6">
                <input type="password" name="repassword" class="form-control  " id="exampleRepeatPassword" placeholder="Repeat Password">
              </div>
            </div>
            <button type="submit" class="btn btn-primary btn-user btn-block">Tambah Admin</button>
          </form>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>
@endsection
@push('scripts')
<script>
$(function() {
    $('#admin').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{route('admin.json_admin')}}",
        columns: [
            { data: 'DT_RowIndex', name: 'DT_RowIndex'},
            { data: 'pic', name: 'pic' },
            { data: 'nama', name: 'nama' },
            { data: 'email', name: 'email' },
            { data: 'ganti_password', name: 'ganti_password', orderable: false, searchable: false},
            { data: 'ganti_foto', name: 'ganti_foto', orderable: false, searchable: false},
            { data: 'ganti_status', name: 'ganti_status', orderable: false, searchable: false},
            { data: 'action', name: 'action', orderable: false, searchable: false},
        ],
    });
});
</script>

@endpush

resources/views/admin/data_post.blade.php
@extends('admin.layout')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Data Post</h1>
        <div class="card shadow mb-4">
            <div class="card-body">
                <a href="{{route('post.form_input_post')}}" class="btn btn-primary">Tambah Post</a>
            </div>
        </div>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Tabel Data Post</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table table-bordered" id="admin" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>NO</th>
                <th>FOTO</th>
                <th>JUDUL</th>
                <th>PENGATURAN</th>
            </tr>
            </thead>
            
        </table>
        </div>
    </div>
    </div>
</div>
<!-- /.container-fluid -->

@endsection
@push('scripts')
<script>
$(function() {
    $('#admin').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{route('post.json_post')}}",
        columns: [
            { data: 'DT_RowIndex', name: 'DT_RowIndex'},
            { data: 'pic', name: 'pic' },
            { data: 'judul', name: 'judul' },
            { data: 'action', name: 'action', orderable: false, searchable: false},
        ],
    });
});
</script>

@endpush

resources/views/admin/form_input_post.blade.php
@extends('admin.layout')

@section('content')

<form action="{{route('post.input_post')}}" method="POST" enctype="multipart/form-data">
@csrf
<div class="row">
<div class="container">
    <div class="col-md-8" >
        <div class="row">
            <div class="col-md-12" style="margin-bottom:20px;">
                
                <div class="form-group">
                    <input placeholder="Judul Posting" type="text" name="judul" class="form-control" required>
                </div>
                
                <textarea id="konten" class="form-control" name="isi" rows="10" cols="50" placeholder="Teori"></textarea>
            </div>
            <div class="col-md-6" style="margin-bottom:20px;">
                <div class="card">
                    <div class="card-header">
                        <h6 class="text-uppercase mb-0">File / Gambar</h6>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label>Gambar :</label>
                            <input type="file" name="pic" id="imgInp" class="form-control" >
                        </div>
                        
                    </div>
                </div>
            </div>
            <div class="col-md-6">
        <div class="row">
            
            <div class="col-md-12" style="margin-bottom:20px;">
                    <div class="card">
                        <div class="card-body">
                            <div class="form-group" ">
                                <button type="submit" class="btn btn-block btn-success"> Kirim </button>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
        </div>
    </div>
    
</div>
</div>
</form>
@endsection
@push('scripts')
<script>
  var konten = document.getElementById("konten");
    CKEDITOR.replace(konten,{
    language:'en-gb'
  });
  CKEDITOR.config.allowedContent = true;
</script>
@endpush

resources/views/admin/form_update_post.blade.php
@extends('admin.layout')

@section('content')

<form action="{{route('post.update_post',$data->id)}}" method="POST" enctype="multipart/form-data">
@csrf
<div class="row">
<div class="container">
    <div class="col-md-8" >
        <div class="row">
            <div class="col-md-12" style="margin-bottom:20px;">
                
                <div class="form-group">
                    <input placeholder="Judul Posting" type="text" value="{{$data->judul}}" name="judul" class="form-control" required>
                </div>
                
                <textarea id="konten" class="form-control" name="isi" rows="10" cols="50" placeholder="Teori">{{$data->isi}}</textarea>
            </div>
            <div class="col-md-6" style="margin-bottom:20px;">
                <div class="card">
                    <div class="card-header">
                        <h6 class="text-uppercase mb-0">File / Gambar</h6>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label>Gambar :</label>
                            <input type="file" name="pic" id="imgInp" class="form-control" >
                        </div>
                        
                    </div>
                </div>
            </div>
            <div class="col-md-6">
        <div class="row">
            
            <div class="col-md-12" style="margin-bottom:20px;">
                    <div class="card">
                        <div class="card-body">
                            <div class="form-group" ">
                                <button type="submit" class="btn btn-block btn-success"> Kirim </button>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
        </div>
    </div>
    
</div>
</div>
</form>
@endsection
@push('scripts')
<script>
  var konten = document.getElementById("konten");
    CKEDITOR.replace(konten,{
    language:'en-gb'
  });
  CKEDITOR.config.allowedContent = true;
</script>
@endpush

resources/views/admin/index.blade.php
@extends('admin.layout')

@section('content')
       
@endsection

resources/views/admin/layout.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>DCO</title>

  <!-- Custom fonts for this template-->
  <link href="{{asset('vendor/fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="{{asset('css/sb-admin-2.min.css')}}" rel="stylesheet">

  <!-- Custom styles for this page -->
  <link href="v{{asset('endor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
  

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    @include('admin.tools.sidebar')

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">
        @include('admin.tools.nav')
        @yield('content')
      @include('admin.tools.footer')
    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Yakin Keluar Ruangan?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Klik "KELUAR" jika benar - benar ingin keluar.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">BATAL</button>
          <a class="btn btn-primary" href="{{route('keluar')}}">KELUAR</a>
        </div>
      </div>
    </div>
  </div>
                <div id="ganti_password" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" class="modal fade text-left">
                            <div role="document" class="modal-dialog">
                                <div class="modal-content">
                                <div class="modal-header">
                                    <h4 id="exampleModalLabel" class="modal-title">Ganti Password</h4>
                                    <button type="button" data-dismiss="modal" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                                </div>
                                <div class="modal-body">
                                    <form action="{{route('admin.update_password',Auth::User()->id)}}" method="post" enctype="multipart/form-data">
                                    @csrf
                                    <div class="form-group">
                                        <input type="password" name="password" class="form-control" required placeholder="Password Baru">
                                    </div>
                                    <div class="form-group">       
                                        <input type="submit" value="Update" class="btn btn-info">
                                    </div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                </div>
                                </div>
                            </div>
                            </div>
  <!-- Bootstrap core JavaScript-->
  <script src="{{asset('vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{asset('vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{{asset('vendor/jquery-easing/jquery.easing.min.js')}}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{{asset('js/sb-admin-2.min.js')}}"></script>
   <!-- Page level plugins -->
   <script src="{{asset('vendor/datatables/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>

  <!-- Page level custom scripts -->
  <script src="http://cdn.ckeditor.com/4.15.0/standard/ckeditor.js"></script>
  @include('alert')

  @stack('scripts')
</body>

</html>