routes/admin.php
<?php
Route::group(['middleware' => ['web','roles']],function(){
    Route::group(['roles'=>['Admin']],function(){
        Route::group([
            'prefix' => 'admin','as' => 'admin.',
        ], function(){
            Route::get('/', 'AdminController@index')->name('admin');
            Route::get('/data_admin','AdminController@data_admin')->name('data_admin');
            Route::get('/json_admin','AdminController@json_admin')->name('json_admin');
            Route::post('/input_admin','AdminController@input_admin')->name('input_admin');
            Route::post('/update_user/{id}','AdminController@update_user')->name('update_user');
            Route::post('/update_foto/{id}','AdminController@update_foto')->name('update_foto');
            Route::get('/update_status/{id}','AdminController@update_status')->name('update_status');
            Route::get('/delete_user/{id}','AdminController@delete_user')->name('delete_user');
        
        });

    });
});
Route::group(['middleware' => ['web','roles']],function(){
    Route::group(['roles'=>['Admin','Guru']],function(){
        Route::group([
            'prefix' => 'admin','as' => 'admin.',
        ], function(){
            Route::post('/update_password/{id}','AdminController@update_password')->name('update_password');
        });

    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/1', function () {
    return view('welcome');
});
Route::get('/link', function () {
    Artisan::call('storage:link');
    }); //untuk membuat storage link
include 'admin.php';
include 'landing.php';
include 'posting.php';

resources/views/admin/tools/footer.blade.php
<!-- Footer -->
<footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy;Coro News 2020</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

resources/views/admin/tools/nav.blade.php
 <!-- Topbar -->
 <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

<!-- Sidebar Toggle (Topbar) -->
<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
  <i class="fa fa-bars"></i>
</button>
 <!-- Topbar Search -->
<h2>DCO</h2> 
<ul class="navbar-nav ml-auto">

  <div class="topbar-divider d-none d-sm-block"></div>

  <!-- Nav Item - User Information -->
  <li class="nav-item dropdown no-arrow">
    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{Auth::User()->nama}}</span>
      <img class="img-profile rounded-circle" src="{{asset('img/logo.svg')}}">
    </a>
    <!-- Dropdown - User Information -->
    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
      <a class="dropdown-item" href="#" data-toggle="modal" data-target="#ganti_password">
        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
        Ganti Password
      </a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
        Logout
      </a>
    </div>
  </li>

</ul>

</nav>
<!-- End of Topbar -->

resources/views/admin/tools/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

<!-- Sidebar - Brand -->
<a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
  <div class="sidebar-brand-icon rotate-n-15">
    <i class="fas fa-laugh-wink"></i>
  </div>
@if((Auth::User()->role_id)==1)
  <div class="sidebar-brand-text mx-3">Admin <sup>2</sup></div>
@else
<div class="sidebar-brand-text mx-3">Guru <sup>2</sup></div>
@endif
</a>

<!-- Divider -->
<hr class="sidebar-divider my-0">

<!-- Nav Item - Dashboard -->
<li class="nav-item active">
  <a class="nav-link" href="{{route('admin.admin')}}">
    <i class="fas fa-fw fa-tachometer-alt"></i>
    <span>Dashboard</span></a>
</li>
<!-- Divider -->
<hr class="sidebar-divider">

<!-- Heading -->
<div class="sidebar-heading">
  Pengguna
</div>
<!-- Nav Item - Pages Collapse Menu -->
<li class="nav-item">
  <a class="nav-link" href="{{route('admin.data_admin')}}">
    <i class="fas fa-fw fa-user"></i>
    <span>Admin</span></a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{{route('post.data_post')}}">
    <i class="fas fa-fw fa-user"></i>
    <span>Posting</span></a>
</li>
<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">

<!-- Sidebar Toggler (Sidebar) -->
<div class="text-center d-none d-md-inline">
  <button class="rounded-circle border-0" id="sidebarToggle"></button>
</div>
</ul>
<!-- End of Sidebar -->